config/routes.rb
FamilyMattersApp::Application.routes.draw do
 
  root :to => "families#index"
  get "families" => "families#index", :as => :home
  post "families" => "families#create"
  get "families/new" => 'families#new'
  get "families/:id" => "families#show", :as => :families
  #get "family/index"
  #get "familys/new"

end

app/models/family.rb
class Family < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/families_controller.rb
class FamiliesController < ApplicationController
  def index
    @allfamilys = Family.all
    
  end

  def show
    
    @allfamilys = Family.find params[:id]
  
  end

  def new
    @allfamilys = Family.new
    # familys.create params[:family]
    #    
    #    redirect_to "familys"
  end
  
  def create
    
   Family.create params[:family]
  
    redirect_to "/families"
  end
  
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/familys_helper.rb
module FamilysHelper
end

app/views/families/index.html.erb
<h1>Family Matters!</h1>

<ul>
  <% @allfamilys.each do | x | %>
  <li><%= link_to x.name, "families/#{x.id}" %></li>
    <% end %>

<ul>
  
<p><%= link_to "Register Now!", "/families/new" %></p>

app/views/families/new.html.erb
<h1>Join Family Matters Now!</h1>

<%= form_for @allfamilys do | f | %> 

<p>

     <%= f.label:name %> 
     <%= f.text_field :name %>
</p>
<p>

     <%= f.label:age %> 
     <%= f.text_field :age %>
</p>

<p>

     <%= f.label:city %> 
     <%= f.text_field :city %>
</p>
<p>

     <%= f.label:email %> 
     <%= f.text_field :email %>
</p>


<p><%= f.submit %></p> 

<% end %>

app/views/families/show.html.erb
<h1><strong><%= @allfamilys.name %></strong> Information:</h1>

<ul>
  <li> Name <%= @allfamilys.name %></li>
  <li> Age <%= @allfamilys.age %></li>
  <li> Location <%= @allfamilys.city %></li>
   <li> Contact <%= @allfamilys.email %> </li>
</ul>

<%= link_to 'Home Page', home_url %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>FamilyMattersApp</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>